

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."question_category" AS ENUM (
    'admission',
    'financial',
    'life',
    'other'
);


ALTER TYPE "public"."question_category" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Suggestions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "content" "json" NOT NULL,
    "college_domain" "text" NOT NULL
);


ALTER TABLE "public"."Suggestions" OWNER TO "postgres";


ALTER TABLE "public"."Suggestions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Suggestions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."colleges" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "domain" "text" NOT NULL,
    "city" "text",
    "state" "text"
);


ALTER TABLE "public"."colleges" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."colleges_collegeid_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."colleges_collegeid_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."colleges_collegeid_seq" OWNED BY "public"."colleges"."id";



ALTER TABLE "public"."colleges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."colleges_collegeid_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."emailaddresses" (
    "emailaddress" "text" NOT NULL,
    "collegeid" integer NOT NULL
);


ALTER TABLE "public"."emailaddresses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."responses" (
    "id" integer NOT NULL,
    "collegeid" integer NOT NULL,
    "response" "text" NOT NULL,
    "questionid" integer NOT NULL
);


ALTER TABLE "public"."responses" OWNER TO "postgres";


ALTER TABLE "public"."responses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questionresponses_responseid_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" integer NOT NULL,
    "question" "text" NOT NULL,
    "category" "text" NOT NULL,
    CONSTRAINT "questions_category_check" CHECK (("category" = ANY (ARRAY['admission'::"text", 'financial'::"text", 'life'::"text", 'other'::"text"])))
);


ALTER TABLE "public"."questions" OWNER TO "postgres";


ALTER TABLE "public"."questions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."questions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Suggestions"
    ADD CONSTRAINT "Suggestions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."colleges"
    ADD CONSTRAINT "colleges_domain_key" UNIQUE ("domain");



ALTER TABLE ONLY "public"."colleges"
    ADD CONSTRAINT "colleges_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."colleges"
    ADD CONSTRAINT "colleges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."emailaddresses"
    ADD CONSTRAINT "email_addresses_pkey" PRIMARY KEY ("emailaddress");



ALTER TABLE ONLY "public"."responses"
    ADD CONSTRAINT "questionresponses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_question_key" UNIQUE ("question");



ALTER TABLE ONLY "public"."Suggestions"
    ADD CONSTRAINT "Suggestions_college_domain_fkey" FOREIGN KEY ("college_domain") REFERENCES "public"."colleges"("domain") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."emailaddresses"
    ADD CONSTRAINT "emailaddresses_collegeid_fkey" FOREIGN KEY ("collegeid") REFERENCES "public"."colleges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."responses"
    ADD CONSTRAINT "questionresponses_collegeid_fkey" FOREIGN KEY ("collegeid") REFERENCES "public"."colleges"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."responses"
    ADD CONSTRAINT "responses_questionid_fkey" FOREIGN KEY ("questionid") REFERENCES "public"."questions"("id") ON DELETE CASCADE;



ALTER TABLE "public"."Suggestions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."questions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON TABLE "public"."Suggestions" TO "anon";
GRANT ALL ON TABLE "public"."Suggestions" TO "authenticated";
GRANT ALL ON TABLE "public"."Suggestions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Suggestions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Suggestions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Suggestions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."colleges" TO "anon";
GRANT ALL ON TABLE "public"."colleges" TO "authenticated";
GRANT ALL ON TABLE "public"."colleges" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colleges_collegeid_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."emailaddresses" TO "anon";
GRANT ALL ON TABLE "public"."emailaddresses" TO "authenticated";
GRANT ALL ON TABLE "public"."emailaddresses" TO "service_role";



GRANT ALL ON TABLE "public"."responses" TO "anon";
GRANT ALL ON TABLE "public"."responses" TO "authenticated";
GRANT ALL ON TABLE "public"."responses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."questionresponses_responseid_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questionresponses_responseid_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questionresponses_responseid_seq" TO "service_role";



GRANT ALL ON TABLE "public"."questions" TO "anon";
GRANT ALL ON TABLE "public"."questions" TO "authenticated";
GRANT ALL ON TABLE "public"."questions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."questions_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
